[smtp]
# Host e porta del tuo server mail.eventmedia.it
server = "mail.eventmedia.it"
port = 993                    # Questa Ã¨ la porta standard per la connessione sicura (TLS/STARTTLS)
sender_email = "timmy@eventmedia.it" # L'indirizzo da cui invii (es. il tuo)
sender_password = "TeamBuilding2025#" # La password dell'account mittente

# Server in entrata: mail.eventmedia.it
# Porta IMAP: 993
# Server in uscita: mail.eventmedia.it
# Porta SMTP: 465
